version: 2.1

parameters:
  build-demo-nest-server:
    type: boolean
    default: false

commands:
  install-dependencies:
    description: Install dependencies with caching, optionally choose package manager.
    parameters:
      pkg-manager:
        type: enum
        enum: ['npm', 'pnpm']
        default: 'npm'
      cache-version:
        type: string
        default: 'v1'
    steps:
      - run:
          name: Check package.json
          command: bash ./apps/demo-nest-server/.circleci/scripts/check-package-json.sh
      - run:
          name: Process lockfile
          command: bash ./apps/demo-nest-server/.circleci/scripts/process-lockfile.sh
      - run:
          name: Ensure package manager
          environment:
            PKG_MANAGER: <<parameters.pkg-manager>>
          command: bash ./apps/demo-nest-server/.circleci/scripts/ensure-pkg-manager.sh
      - restore_cache:
          keys:
            - node-deps-{{ arch }}-<<parameters.cache-version>>-{{ .Branch }}-{{ checksum "/tmp/node-project-lock" }}
      - run:
          name: Install dependencies
          environment:
            PKG_MANAGER: <<parameters.pkg-manager>>
          command: bash ./apps/demo-nest-server/.circleci/scripts/install-dependencies.sh
      - when:
          condition:
             equal: [npm, <<parameters.pkg-manager>>]
          steps:
            - save_cache:
                key: node-deps-{{ arch }}-<<parameters.cache-version>>-{{ .Branch }}-{{ checksum "/tmp/node-project-lock" }}
                paths:
                  - ~/.npm
      - when:
          condition:
             equal: [pnpm, <<parameters.pkg-manager>>]
          steps:
            - save_cache:
                key: node-deps-{{ arch }}-<<parameters.cache-version>>-{{ .Branch }}-{{ checksum "/tmp/node-project-lock" }}
                paths:
                  - ~/.pnpm-store

jobs:
  run-script:
    description: Run scripts defined inside package.json
    parameters:
      node-version:
        type: string
        default: 'lts'
      pkg-manager:
        type: enum
        enum: ['npm', 'pnpm']
        default: 'npm'
      cache-version:
        type: string
        default: 'v1'
      package:
        type: string
        default: ''
      script:
        type: string
        default: ''
    docker:
      - image: cimg/node:<<parameters.node-version>>
    resource_class: large
    steps:
      - checkout
      - install-dependencies:
          pkg-manager: <<parameters.pkg-manager>>
          cache-version: <<parameters.cache-version>>
      - run:
          name: Run <<parameters.pkg-manager>> <<parameters.script>>
          environment:
            PKG_MANAGER: <<parameters.pkg-manager>>
            PACKAGE: <<parameters.package>>
            SCRIPT: <<parameters.script>>
          command: bash ./apps/demo-nest-server/.circleci/scripts/run-script.sh

workflows:
  lint:
    when: <<pipeline.parameters.build-demo-nest-server>>
    jobs:
      - run-script:
          name: Lint
          pkg-manager: pnpm
          package: demo-nest-server
          script: lint
  test-unit:
    when: <<pipeline.parameters.build-demo-nest-server>>
    jobs:
      - run-script:
          name: Unit Tests
          pkg-manager: pnpm
          package: demo-nest-server
          script: test





